LH.add({id:'postgresql',icon:'🐘',title:'PostgreSQL DBA',desc:'From first install to advanced DBA work, with Oracle equivalents.',phases:[
['Foundations',['What PostgreSQL is: architecture, processes and shared memory','Installation, initdb, and cluster vs database vs schema','psql basics and meta-commands, pgAdmin and DBeaver','Directory layout: PGDATA and configuration files']],
['SQL and Database Objects',['Data types: numeric, text, date/time, UUID, arrays, JSONB, enums, ranges','DDL and DML, including UPSERT (ON CONFLICT)','Constraints: PK, FK, UNIQUE, CHECK, NOT NULL, EXCLUDE','Queries: joins, subqueries, CTEs, window functions, LATERAL','Sequences, identity columns, views, materialized views, temp tables','Schemas and search_path','Full-text search and pg_trgm']],
['Programmability',['PL/pgSQL: functions, procedures, control flow, exceptions, cursors','Triggers (row, statement, event) and rules','Extensions: pg_stat_statements, pgcrypto, postgres_fdw, PostGIS, pg_cron','Foreign data wrappers (like Oracle DB links)']],
['Transactions and Concurrency',['ACID, isolation levels and MVCC','Locking: row, table, advisory locks and deadlocks','Dead tuples, bloat and transaction ID wraparound','VACUUM, autovacuum, ANALYZE and VACUUM FULL']],
['Indexing and Performance Tuning',['Index types: B-tree, Hash, GIN, GiST, SP-GiST, BRIN','Partial, expression, covering and multicolumn indexes','EXPLAIN and EXPLAIN (ANALYZE, BUFFERS)','Planner statistics, pg_stats and extended statistics','Memory tuning: shared_buffers, work_mem and friends','Query monitoring: pg_stat_activity, pg_stat_statements, auto_explain','Partitioning: range, list, hash and pruning']],
['Security and Administration',['Roles, privileges, GRANT/REVOKE and row-level security','Authentication: pg_hba.conf, SCRAM, SSL/TLS, LDAP/Kerberos','Tablespaces, pg_catalog, information_schema and system views','Logging configuration and pgBadger','Upgrades: minor vs major, pg_upgrade, dump/restore']],
['Backup, Recovery and HA',['Logical backups: pg_dump, pg_dumpall, pg_restore','Physical backups: pg_basebackup, WAL archiving, PITR','pgBackRest and Barman (the RMAN equivalents)','Streaming replication, slots and cascading replicas','Logical replication: publications and subscriptions','Failover and HA: Patroni, repmgr, HAProxy','Connection pooling: PgBouncer and pgpool-II']],
['Advanced Topics',['WAL internals, checkpoints and pg_waldump','Parallel query, JIT and table access methods','Large-scale design: sharding, Citus, TimescaleDB','Monitoring stack: Prometheus, postgres_exporter, Grafana, pgwatch','Troubleshooting: bloat, long transactions, lag, locks, wraparound','Capacity planning and benchmarking with pgbench']],
['PostgreSQL in the Cloud',['Azure Database for PostgreSQL Flexible Server','AWS RDS/Aurora PostgreSQL and Google Cloud SQL','Migration from Oracle: ora2pg, type mapping, PL/SQL conversion, Azure DMS']]]});
