LH.add({id:'redshift',icon:'🚀',title:'Amazon Redshift DBA',desc:'Columnar MPP warehouse, from fundamentals to production operations.',phases:[
['Foundations',['Data warehouse vs OLTP: OLAP, star and snowflake schemas','Columnar storage and why it suits analytics','Massively parallel processing (MPP) architecture','Cluster anatomy: leader node, compute nodes, slices','Node types: RA3, DC2 and Redshift Serverless','AWS basics: IAM, VPC, subnets, security groups, S3, CloudWatch','First cluster or workgroup, and connecting with clients']],
['SQL and PostgreSQL Basics in Redshift',['Data types and their limits','DDL: databases, schemas, tables, views','DML: INSERT, UPDATE, DELETE, MERGE','Joins, subqueries, CTEs and window functions','Redshift SQL differences from PostgreSQL','System catalog: pg_*, information_schema, SVV/SVL/STL/STV/SYS views']],
['Table Design and Performance Fundamentals',['Distribution styles: KEY, ALL, EVEN, AUTO','Sort keys: compound, interleaved, automatic','Compression encodings','Primary and foreign keys as planner hints','Design best practices and automatic table optimization','Data skew and how to detect it']],
['Loading and Unloading Data',['COPY from S3, DynamoDB, EMR and remote hosts','File formats: CSV, Parquet, ORC, JSON and compression','Manifest files, error handling and STL_LOAD_ERRORS','Auto-copy from S3','UNLOAD to S3','Zero-ETL and streaming ingestion','AWS Glue, DMS and ETL options','Staging tables and upsert patterns']],
['Security and Access Control',['Users, groups, roles and privileges','Row-level security and dynamic data masking','IAM integration, federated login and temporary credentials','Encryption at rest and in transit','VPC, enhanced VPC routing and access modes','Audit logging and CloudTrail']],
['Routine Maintenance',['VACUUM types and automatic vacuum','ANALYZE and automatic analyze','Ghost rows and the unsorted region','Disk space management and the 80% full problem','Deep copy vs vacuum tradeoffs','Maintenance utilities (amazon-redshift-utils)']],
['Workload Management and Concurrency',['Automatic vs manual WLM','Queues, assignment rules, priority and QMR','Short query acceleration (SQA)','Concurrency scaling','Query slots and memory allocation','Serverless RPUs and capacity']],
['Query Performance Tuning',['Reading EXPLAIN plans: DS_DIST_*, DS_BCAST_*','Execution stages: segments, steps and streams','Finding slow and queued queries','Alerts: STL_ALERT_EVENT_LOG','Result cache and compile cache','Materialized views and auto-refresh','Join, aggregation and predicate tuning']],
['Backup, Recovery and High Availability',['Automated and manual snapshots','Cross-region snapshot copy','Restoring a cluster or a single table','Serverless snapshots and recovery points','Multi-AZ deployments','Resize: elastic vs classic','Cluster relocation, maintenance windows and tracks']],
['Monitoring and Troubleshooting',['Console metrics and CloudWatch alarms','Common issues: disk full, deadlocks, stuck queries','Locks and blocking sessions','Terminating sessions','AWS Support and diagnostic data']],
['Data Lake and Federated Querying',['Redshift Spectrum and external schemas','Glue Data Catalog and Lake Formation','Partitioning external data','Federated queries to RDS/Aurora','Apache Iceberg and Hudi tables']],
['Advanced Features',['Datashares: cross-cluster, account, region','Redshift ML','Stored procedures and UDFs','SUPER type and PartiQL','Geospatial data','Redshift Data API','Cross-database queries','Scheduled queries']],
['Cost, Automation and Operations',['Pricing models: on-demand, reserved, serverless','Pause/resume and usage limits','Infrastructure as code and CI/CD','Capacity planning and sizing','Migrations with AWS SCT and DMS']]]});
